# Loads the default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  resource_mode: yaml
  resources:
    - url: /local/swiss-public-transport-card/swiss-public-transport-card.js
      type: module
